# _*_coding:utf-8_*_

sites = [
    # "http://magicmining.sinaapp.com/chat",
    # "http://www.baidu.com",
    # 没有提交按钮 是超链接 可以通过构造参数提交 "http://tieba.baidu.com/",
    # "http://127.0.0.1/dvwa/vulnerabilities/xss_r/",
    # 没有表单 直接从input提交 "http://www.u17.com",
    # 复杂页面 多个搜索类别共用一个表单 通过hidden参数改变类别 同时搜索值也是一个hidden参数 由脚本更改后提交 "http://www.sina.com.cn/",
    # 没有表单 但可以提交意见 "http://cbg.baidu.com/?sc=1000020",
    # 复杂页面 "http://map.baidu.com",
    # 无法打开 "http://weibo.com/",
    # 有post表单 "http://www.sohu.com/",
    # 无法打开 "http://www.qq.com/",
    # 可以改 "http://www.iqiyi.com/",
    # 复杂页面 报错 "http://www.ifeng.com",
    # "http://www.autohome.com.cn",
    # "http://www.eastmoney.com",
    # 没有找到表单 "http://www.fang.com/",
    # 报错 "http://www.ctrip.com",
    # "http://www.qunar.com/",
    # 报错 "http://www.ganji.com/",
    # 有post表单 "http://www.lianjia.com/",
    # 没有表单 "http://www.meipai.com",
    # 参数太多无法模拟提交 "http://www.zhaopin.com",
    # radio "http://www.ccb.com/",
    # 没有表单 通过点击span提交 "http://www.kaola.com/?__da_wH4H6k_geWAxF",
    # 超时 "http://www.17173.com/",
    # 超时 "http://military.china.com/zh_cn/",
    # 超时 "http://www.xinjunshi.com/",
    # "http://www.hupu.com/",
    # "http://www.zhenai.com/", 存在漏洞
    # "http://www.fang.com",
    # "http://www.78.cn/?sid=1102",
    "http://www.pcauto.com.cn/",
    "http://www.bitauto.com/",
    "http://www.xcar.com.cn/",
    "http://www.gdxxb.com/85763",
    "http://www.gdxxb.com/85762",
    "http://cdn.919377.com/welcome.html?id=6829",
    "http://zt.ztgame.com/url/hao.html",
    "http://www.10086.cn/",
    "http://www.10010.com/",
    "http://www.189.cn/",
    "http://www.zol.com.cn/",
    "http://mobile.pconline.com.cn/",
    "http://www.18183.com/",
    "http://www.feng.com/",
    "http://zs.91.com/co/bd/",
    "http://www.tuniu.com/",
    "http://www.LY.com",
    "http://www.elong.com/",
    "http://www.stockstar.com/",
    "http://www.10jqka.com.cn/",
    "http://www.hexun.com/",
    "http://www.itouzi.com",
    "http://www.jimubox.com",
    "http://www.renrendai.com",
    "http://www.eastmoney.com/",
    "http://www.yooli.com",
    "http://www.souyidai.com",
    "http://www.haodai.com",
    "http://www.yztz.com",
    "http://www.rayli.com.cn/",
    "http://www.mogujie.com",
    "http://www.zhcw.com/",
    "http://www.icbc.com.cn/",
    "http://www.ccb.com/",
    "http://www.abchina.com/",
    "http://www.boc.cn/",
    "http://www.bankcomm.com/",
    "http://www.cmbchina.com/",
    "http://www.zhaopin.com/",
    "http://www.51job.com/",
    "http://www.ganji.com/zhaopin/",
    "http://www.liepin.com/abtest/38/",
    "http://www.yingjiesheng.com/",
    "http://www.58.com/?path=job.shtml",
    "http://www.youqudian.com/c_5/3711.html",
    "http://www.baihe.com/",
    "http://www.69xiu.com/extension/speadRoom?jxiusr=baidu_web_m5",
    "http://www.zhibo8.cc/",
    "http://mail.163.com/",
    "http://mail.126.com/",
    "http://mail.aliyun.com/",
    "http://mail.sina.com.cn/",
    "http://mail.qq.com/",
    "http://www.qidian.com/",
    "http://www.xxsy.net/",
    "http://www.1ting.com/",
    "http://www.kugou.com/",
    "http://www.kuwo.cn/",
    "http://www.tianya.cn/",
]